server:
  port: 7900 # tomcat 端口，程序启动的端口
spring:
  application:
    name: provider-user # 程序名字
eureka:
  client:
    serviceUrl:
      defaultZone: http://pan:pan@127.0.0.1:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    appname: provider-user