server:
  port: 8900 # tomcat 端口，程序启动的端口
spring:
  application:
    name: consumer-order # 程序名字
eureka:
  client:
    serviceUrl:
      defaultZone: http://pan:pan@127.0.0.1:8761/eureka/
user:
  url: http://localhost:7900/user/